version: 0.2
   
phases:
  install:
    commands:
      - echo "Iniciando Build"
  pre_build:
    commands:
      - echo "Iniciando Pré Build"
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - ls -l
